CREATE TABLE IF NOT EXISTS usr
(
    id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(255) NOT NULL UNIQUE,
    email    varchar(255) NOT NULL UNIQUE,
    password varchar(255) NOT NULL,
    role     varchar(255) NOT NULL

        CONSTRAINT usr_role_check CHECK (role IN ('USER', 'ADMIN'))
);
